### ISSUE TITLE
Pre-move checklist

### ISSUE THREAD

**Issue by 1480c1** [AOMediaCodec/SVT-AV1#1429]
List of tasks that probably should be done or at least addressed in some way before we move the repo to under the new location, contributors and others, feel free to either directly edit this issue or add a comment on what you might think should be added to the list.

- [ ] Make sure GitHub Actions works even with the new location URL (Make sure all references to OpenVisualCloud/SVT-AV1 either use repo agnostic GitHub variables or just hardcode to the new location)
- [ ] Don't use globs for CMakeLists.txt (https://github.com/OpenVisualCloud/SVT-AV1/pull/1193)
- [ ] Consider adding a more robust and reliable API versioning system (https://github.com/OpenVisualCloud/SVT-AV1/issues/1417)
- [ ] Finish/Cleanup documentation (https://github.com/OpenVisualCloud/SVT-AV1/pull/1241, ~~https://github.com/OpenVisualCloud/SVT-AV1/issues/1284~~, ~~https://github.com/OpenVisualCloud/SVT-AV1/issues/1272~~, https://github.com/OpenVisualCloud/SVT-AV1/issues/1008, ~~https://github.com/OpenVisualCloud/SVT-AV1/issues/1061~~, ~~https://github.com/OpenVisualCloud/SVT-AV1/issues/984~~)
  - Might be a good idea to convert our plain text function documentation that's next to a lot of functions to doxygen style docs or some other standard way
- [ ] Add a `--version` flag (https://github.com/OpenVisualCloud/SVT-AV1/issues/1213)
- [ ] Clean up all macros that create dead code (Most of them are located in EbDefinitions.h)
- [ ] General Code cleanup (https://github.com/OpenVisualCloud/SVT-AV1/issues/326) (Would be nice if we could get rid of a lot of the `(void)arg;` lines we have)
  - I noticed we actually have a lot of duplicate functions, just with different names (`aom_....`, `svt_aom....`, `eb_aom...`), some internally have the same exact code, just maybe with `uint16_t *` instead of `uint8_t *` in the function declaration, even though it still casts the `uint8_t *` to `uint16_t *` internally
- [ ] Make sure clang-format has been run for all files (Currently have seen a lot of files with clang-format excluded still)
- [ ] Clean up global symbols and make sure all global symbols are prefixed or static or not a symbol that might conflict (https://github.com/OpenVisualCloud/SVT-AV1/issues/572)
  - An alternative way to generate a symbol list is `nm --defined-only -CAg Bin/Release/libSvtAv1Enc.a | cut -d' ' -f 3 | sort -u` inside bash

there's still a lot related to the SvtAv1EncApp

Some ideas that are necessarily a priority:

- Maybe add a way to parse options within the library similar to `-x264-params` and `-x265-params` so that way we don't have to expose every single option inside the ffmpeg wrapper etc
- Maybe consider adding a thread limit option so we can use ffmpeg's `-threads` option (currently instead of threads, we are binding to logical cores using `--lp` which means `--lp 1` on a hyper-threaded system == %200 cpu usage for Linux at least) (this is probably wrong since it's not very clear to me as to what the difference between a single thread and a single "logical processor" would be, so if someone who knows more about this could comment, it would probably be better)
- Clean up/Optimize the structs, since currently, we have a lot of wasted space due to padding and also a lot of wasted space for using `uint32_t`s for essentially boolean options, tied to ` General Code cleanup (#326)`
- Clean up SvtAv1EncApp interface in general
