### ISSUE TITLE
CI: GitHub Actions tracking issue

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#873]
A tracking issue for the development of the GitHub Actions Workflows. Take on any issue from the to-do list you like!

**Done**
 - [x] Initial workflow [#871, @EwoutH]
 - [x] Move Style check from Travis to Actions [#897, @1480c1]
 - [x] Create jobs for different compilers (GCC 7, GCC 8, ~~GCC 9~~, Clang) [#914, @ePirat]
 - [x] Implement quick binary check (check for bitstream changes between PR and master) [#947, @ultrawide]
 - [x] Run on different platforms (~~Ubuntu~~, macOS, ~~Windows~~) [#931, @1480c1]
 - [x] Implement caching
 - [x] Implement compiling the FFmpeg and GStreamer patches (#983, @luigi311)
 - [x] Implement Unit Tests (#967, @Cidana-Developers)

**To-do**
 - [ ] Run with different SIMD levels enabled (sse2, ssse3, sse4.1, avx2, avx512)

**Under consideration**
 - Gather and output full encoding quality and performance metrics (see [visual metrics](https://github.com/google/compare-codecs/blob/master/lib/visual_metrics.py), lots of CPU needed)
 - Deploy pre-compiled builds to GitHub (currently AppVeyor does this on tags/releases)
 - Run style test (currently Travis)
 - Run valgrind (currently Travis)

It's possible to create more than one workflow, so maybe we should create workflows for compile, test, etc. and run those on different platforms. GitHub Actions is brand new and all major functions are covered by Travis, so feel free to experiment. 

I found [Workflow syntax for GitHub Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions) quite useful.

If you have anything that should be added to the list please comment!

**Comment by 1480c1** [comment]
> * Run with different SIMD levels enabled (sse2, ssse3, sse4.1, avx2, avx512)

https://github.com/OpenVisualCloud/SVT-AV1/pull/785

> * Implement caching

https://github.com/actions/cache


I particularly still can't figure out github cache yet

**Comment by ultrawide** [comment]
Sorry, if this may be obvious. I'm new to CI and I'm reading through the docs at the moment, it looks like workflows are ran on GitHub-hosted runners or self-hosted runners. Not sure where to find the answer to this, but I'm curious where our workflows are ran on? For example, if we merge #871 `runs-on: ubuntu-latest`, where will the workflow be hosted? Thanks!

**Comment by 1480c1** [comment]
> Sorry, if this may be obvious. I'm new to CI and I'm reading through the docs at the moment, it looks like workflows are ran on GitHub-hosted runners or self-hosted runners. Not sure where to find the answer to this, but I'm curious where our workflows are ran on? For example, if we merge #871 `runs-on: ubuntu-latest`, where will the workflow be hosted? Thanks!

The workflows should be hosted on GitHub hosted runners, which are probably on Azure or AWS or GCP

**Comment by 1480c1** [comment]
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/hosting-your-own-runners

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-self-hosted-runners-in-a-workflow

Running on self-hosted machines require a special argument to the `runs-on:` tag

**Comment by ePirat** [comment]
Regarding running the tests, should those be run for each compiler in the matrix or should we create a separate action that just compiles once with a specific compiler (which?) and then do the tests?

**Comment by 1480c1** [comment]
Although in the end it will depend on what machines @hassount will add to GitHub actions, I think it maybe fine to keep the compile jobs separate and run the tests as a separate job, probably using gcc-9 or the latest available clang since there shouldn't be too much run time discrepancies between versions. Although ideally, we would test on the default common version and the latest version available to weed out any compiler quirks, depending on the testing load, it may take too long.

Some comparisons between GCC versions: https://www.phoronix.com/scan.php?page=article&item=gcc5-gcc10-benchmarks&num=1

**Comment by ePirat** [comment]
Actually maybe the "full" test with all compilers could be run only each night or so? That way breakages would still be noticed without having it to run for each commit.

**Comment by 1480c1** [comment]
That would be good

**Comment by hassount** [comment]
@ePirat @1480c1 
Sounds good let’s do gcc 9 for all PRs and a nightly for all of them.

**Comment by 1480c1** [comment]
> @ePirat @1480c1
> Sounds good let’s do gcc 9 for all PRs and a nightly for all of them.

Okay, @ePirat or @ultrawide , do one of you guys want to try to it or should I?

**Comment by ePirat** [comment]
@1480c1 I would like to work on this, yes.

**Comment by 1480c1** [comment]
@ePirat and @ultrawide, I will work on moving some of the windows builds to github actions from appveyor

**Comment by hassount** [comment]
Happy New Year everyone :) 

Would github action have a mac platform ?

**Comment by 1480c1** [comment]
Also, @ultrawide, https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#cloud-hosts-for-github-hosted-runners

`GitHub hosts Linux and Windows runners on Standard_DS2_v2 virtual machines in Microsoft Azure with the GitHub Actions runner application installed. The GitHub-hosted runner is a fork of the Azure Pipelines Agent. For more information about the Standard_DS2_v2 machine resources, see "DSv2-series" in the Microsoft Azure documentation.`

@hassount Happy New Years
`GitHub uses MacStadium to host the macOS runners.`

**Comment by ultrawide** [comment]
Thanks for the update @1480c1 

I'll look into working on the below:
> Implement quick binary check (check for bitstream changes between PR and master)

**Comment by ultrawide** [comment]
@1480c1 Hi Christopher, I wanted to confirm with you if we want to use separate jobs for running a binary identical test as per:

>   I think it maybe fine to keep the compile jobs separate and run the tests as a separate job

It looks like I will need to upload the artifacts (encoder binary + library) built in the 'build' job and download the artifacts respectively since each job runs in a separate VM. For the video clips, are you aware of a good method to retrieve the clips or place them somewhere convenient? Thanks!

**Comment by 1480c1** [comment]
> I wanted to confirm with you if we want to use separate jobs for running a binary identical test as per:
> 
> > I think it maybe fine to keep the compile jobs separate and run the tests as a separate job
> 
> It looks like I will need to upload the artifacts (encoder binary + library) built in the 'build' job and download the artifacts respectively since each job runs in a separate VM

Yeah, that probably would be the best by using https://github.com/actions/upload-artifact and https://github.com/actions/download-artifact to upload and download the encoder binary and lib from the gcc-9 job into a separate r2r test job.

You could do something like tar-ing the two files since their action will zip it up for you. That would help with implementing future tests too, depending on @ePirat.



> For the video clips, are you aware of a good method to retrieve the clips or place them somewhere convenient? Thanks!

For travis-ci, we are currently using https://github.com/OpenVisualCloud/SVT-AV1/blob/f402a64ff2bccc7bc6db023a2a18480fc93c61c2/.travis.yml#L53-L54
to download a tar.gz archive of `Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m`, `akiyo_cif.y4m`, and `bus_cif.y4m` as some small test files. You could also use upload-artifacts with them too, either in the build or the first test to run

**Comment by ePirat** [comment]
So I've been working on adding tests to the CI and noticed the Unit tests take forever to run, is that expected? (It now already runs for about an hour)

**Comment by 1480c1** [comment]
> So I've been working on adding tests to the CI and noticed the Unit tests take forever to run, is that expected? (It now already runs for about an hour)

Yes, they do take a really long time sadly

**Comment by ePirat** [comment]
@1480c1 Do we want to anyway run them for each push and PR? Likely that way it would quickly run into the limits of Github Actions free usage plan.

**Comment by 1480c1** [comment]
I would say we probably should only run them on each push to a branch and not for PRs. Although I'm not sure if we want to do push to branches on this repo since this repo has a lot of active branches

**Comment by ePirat** [comment]
@1480c1 Quick update: The tests are now running for nearly 5 hours and still going, given the usage limit of Github actions machines is roughly 33h per month it means we probably can't even run the tests 5 times before hitting the limit, per month.

**Comment by ePirat** [comment]
Is there a less expensive mode to run the unittest or some filter to only run a smaller subset of tests?
Why do the tests take so long? 6 hours seems really really long for just unit tests?

**Comment by hassount** [comment]
adding @Cidana-Developers @andrey-norkin for the discussion to see how we can optimize the unit test runs.

**Comment by ePirat** [comment]
Another thing I noticed is that multiple tests seem to fail: https://github.com/ePirat/SVT-AV1/commit/7098a34da8ac167c261a744e10d109f2ec65bb11/checks?check_suite_id=388262067#step:5:81429

**Comment by 1480c1** [comment]
@Cidana-Developers or @andrey-norkin, looking through libaom_dependency.cmake, is there any particular reason why we are building both MinSizeRel and Debug configs for what is assumed to be MSVC?

**Comment by 1480c1** [comment]
> limit of Github actions machines is roughly 33h per month it means we probably can't even run the tests 5 times before hitting the limit, per month

@ePirat, I believe the 33h per month limit only applies to private repos as https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions
```none
GitHub Actions usage is free for public repositories. For private repositories, each GitHub account receives a certain amount of free minutes and storage, depending on the product used with the account
```

and on both my personal account and github organization, under billing, it only shows the 2000 minutes for private repos

**Comment by ePirat** [comment]
@1480c1 Indeed I believe you are right. But there is still a timeout after 6h which seems to always apply, so it needs to be made faster.

**Comment by hassount** [comment]
@andrey-norkin @Cidana-Developers

**Comment by Cidana-Developers** [comment]
> @Cidana-Developers or @andrey-norkin, looking through libaom_dependency.cmake, is there any particular reason why we are building both MinSizeRel and Debug configs for what is assumed to be MSVC?

libaom is linked by SvtAv1E2eTest for a reference decoder. In MSVC, debug version should link to debug library of libaom, otherwise it reports link errors. That's why we setup for both debug and release version in CMake for MSVC.

**Comment by Cidana-Developers** [comment]
We tested running unit tests in Travis CI with google test shard mode. By distributing unit tests in multiple shards they can walk-around the time limitation of Travis CI Job (50 mins).

Following are the results:
[Unit Tests Pass](https://travis-ci.com/Cidana-Developers/SVT-AV1/builds/144864615)
By disabled following failed test cases:
*AV1WienerConvolveHbdTest*, *HBDVarianceTest*, *AV1HbdJntConvolve2DTest* (fixed in #954 )
*Extsad_CalculationTest*, *sad_CalculationTest* (still in checking)

[Unit Tests Failed](https://travis-ci.com/Cidana-Developers/SVT-AV1/builds/144847955)
Full unit tests

**Comment by spawlows** [comment]
I propose to separate the job "Unit Tests" on travis-ci for 3 separate jobs.
```
      cd $ TRAVIS_BUILD_DIR / Build / linux / $ {build_type: -Release}
           make TestVectors
           cd $ TRAVIS_BUILD_DIR
           SvtAv1UnitTests
           SvtAv1ApiTests
           SvtAv1E2ETests
```

Run separate:
 -SvtAv1UnitTests
 -SvtAv1ApiTests
 -SvtAv1E2ETests


Because when SvtAv1UnitTests not failing fast, then SvtAv1ApiTests
SvtAv1E2ETests will be omitted by limiting the duration of the job on travis.

**Comment by luigi311** [comment]
Is caching still something we want to implement? Looks like it really only takes about 1 minutes to install all dependencies so we wont really be saving much time. The only thing that takes a really long time is the windows build and its really only 2 minutes to get the environment all setup and the rest is it building.

**Comment by luigi311** [comment]
I can go ahead and work on implementing the ffmpeg and gstreamer action if no one else is working on it. I can get started on it as soon as #980 gets merged so i have a good base script.

**Comment by 1480c1** [comment]
> Is caching still something we want to implement? Looks like it really only takes about 1 minutes to install all dependencies so we wont really be saving much time. The only thing that takes a really long time is the windows build and its really only 2 minutes to get the environment all setup and the rest is it building.

I'm not sure if it's necessary anymore since it seems that github action's startup time is relatively low compared to travis-ci so there's not much time to be saved with caching

**Comment by 1480c1** [comment]
> I can go ahead and work on implementing the ffmpeg and gstreamer action if no one else is working on it

That would be good if we can move that off travis-ci. One of my concern would be ffmpeg build times, but at the same time, I'm not very convinced by github action's caching (Would work with static files that are never modified, deb files maybe)

**Comment by luigi311** [comment]
> That would be good if we can move that off travis-ci. One of my concern would be ffmpeg build times, but at the same time, I'm not very convinced by github action's caching (Would work with static files that are never modified, deb files maybe)

Yeah that might be a good candidate for caching. We can cache the full build and just tell it to recompile since make is so smart it will only rebuild the files it needs and reduce the amount of time it takes to rebuild on each following build. I will first build it normally and see how it goes, if it does take a long time I'm going to need to read into how to use githubs caching.

**Comment by luigi311** [comment]
@ultrawide 
There seems to be issues with the binary comparison every once in a while.
Ive been making a lot of changes on my own fork to the svt-av1 github actions to add gstreamer and ffmpeg without modifying any source code or the binary-identical-test job and every once in a while it will fail the check. This seems to only happen once in a blue moon but still raises the question on why is it failing sometimes and not other times. Here is a link to my commit that caused it to fail and that commit consisted of cleaning up the ffmpeg job.
https://github.com/luigi311/SVT-AV1/runs/413241458?check_suite_focus=true

**Comment by luigi311** [comment]
In case anyone is wondering there will not be support for variable names in the uses clause. I was hoping this would get implemented so it would be easy to use the same version of a action throughout all the jobs and will only require us to change it at the very top but they said this will not be implemented.  
https://github.community/t5/GitHub-Actions/Env-variables-in-uses/m-p/44441/highlight/false#M5767

**Comment by ultrawide** [comment]
> @ultrawide
> There seems to be issues with the binary comparison every once in a while.
> Ive been making a lot of changes on my own fork to the svt-av1 github actions to add gstreamer and ffmpeg without modifying any source code or the binary-identical-test job and every once in a while it will fail the check. This seems to only happen once in a blue moon but still raises the question on why is it failing sometimes and not other times. Here is a link to my commit that caused it to fail and that commit consisted of cleaning up the ffmpeg job.
> https://github.com/luigi311/SVT-AV1/runs/413241458?check_suite_focus=true

Thanks for letting me know! I'll investigate it 👍

**Comment by ultrawide** [comment]
Hard to say at the moment. I rebuilt the binary based on master to check for bit stream changes on the failing clip (Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m). It looks okay on my side from a Win10 machine. I'm not able to reproduce it. Open for suggestions if anyone has ideas on how to proceed. 

Command issued:
> SvtAv1EncApp.exe -i Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m -n 3 -b output.ivf

**Comment by luigi311** [comment]
Yeah its weird since it has only appeared like maybe 3 times in the 80 different commits i have pushed. It might just be a github issue at this point.

**Comment by luigi311** [comment]
Heres another example of it failing when all that changed was compression of images in the doc folder
https://github.com/OpenVisualCloud/SVT-AV1/runs/414096956

**Comment by luigi311** [comment]
#983 Adds support for FFMPEG and Gstreamer along with ccache for caching the builds for the following steps:
build (all compilers)
gstreamer
ffmpeg
I tried not to touch the binary test since that one will randomly decided to not work lol

**Comment by ePirat** [comment]
@luigi311 On mismatch we could upload both files as artifacts so those can be inspected manually to figure out whats wrong.

**Comment by mafonsoN** [comment]
Hey @luigi311 @ultrawide it seems that Github Actions' binary identical test is failing due to a bug. I believe the libraries are not being correctly linked when running the branch and master executables.
Here is an example where the master is failing for a branch where new CL parameters were added: https://github.com/OpenVisualCloud/SVT-AV1/pull/963/checks?check_run_id=413615745
Could you please have a look? Thanks!

**Comment by luigi311** [comment]
I think it might be extracting in place where master was built and replacing some files with the new files from the gcc-9 build and thus referencing something that doesnt exist and causing other issues. Thats the only reason i can think of that would cause the master build to reference a flag that does not exist that was added in current. Thoughts @ultrawide ? From some testing earlier each name in a step kinda has its own instance where it will cd you back to the start and wipes any exports you made that are not global env variables. Heres a github test repo for actions that i started right now to mess around with. 
https://github.com/luigi311/Testing-Github-Actions/runs/418199531?check_suite_focus=true

**Comment by ultrawide** [comment]
Thanks @luigi311. Yes, I've been investigating and I got the same conclusion as you. It looks the library is being overwritten and we see a linker error, but I need to confirm. I'm working on a solution right now on a local branch, and hope to update soon.

**Comment by ultrawide** [comment]
@luigi311, I've Re-ordered the steps when performing the binary identical test:
1. Install dependencies
2. Download clips
3. Setup and encode master
4. Setup and encode current
5. Binary compare
6. Upload master as an artifact if the above steps fail for debugging purposes

I'm running into a problem when running the SVT-AV1 artifact from the build job: 
> error while loading shared libraries: libSvtAv1Enc.so.0: cannot open shared object file: No such file or directory

When printing out the dynamic dependencies, it looks like the executable lost its reference to the shared library.
> /home/runner/current/Bin/Release/SvtAv1EncApp:
> 	linux-vdso.so.1 (0x00007ffd3dd1c000)
> 	libSvtAv1Enc.so.0 => not found

Any thoughts on how to proceed?

I've been working on this branch: https://github.com/ultrawide/SVT-AV1/tree/binary-compare 
An example of the failure: https://github.com/ultrawide/SVT-AV1/runs/423883701

**Comment by 1480c1** [comment]
Perhaps make it so that it only compiles as static all the way? (`-DBUILD_SHARED_LIBS=OFF`)

**Comment by kylophone** [comment]
@ePirat, another thing to consider is our coveralls job. Not sure if that's on your radar.

**Comment by ePirat** [comment]
@kylophone Hi, it is not currently, what to consider about that?

**Comment by ultrawide** [comment]
Hi @EwoutH, I'm interested in working on the below if there's demand
> Gather and output full encoding quality and performance metrics (see visual metrics, lots of CPU needed)

It looks like we already have [https://videocodectracker.dev/]. Can you give me more details and requirements?

**Comment by kylophone** [comment]
> @kylophone Hi, it is not currently, what to consider about that?

It should be possible to run all of the unit tests with `llvm-cov`/`gcov` and post the results to coveralls. This was being worked on a few weeks ago, but paused. See: https://github.com/OpenVisualCloud/SVT-AV1/pull/889 for more info. Since we will be sharding our unit tests, this might add a bit of extra complexity, but hopefully it's still possible.

**Comment by EwoutH** [comment]
@ultrawide Thanks for the interest! I think it would be really useful to be able to quickly compare PRs against the master branch in terms of speed and quality.

In an ideal scenario, you could open a PR, request a comparison against the master branch (with a tag, keyword or label for example), and get a report back on the overall changes. https://beta.arewecompressedyet.com/ does that ([example](https://beta.arewecompressedyet.com/?job=SVT-AV1-enc-mode-4%402019-12-03&job=SVT-AV1-enc-mode-4%402019-12-18)), but you need to request it manually, can only compare one setting at a time and it isn't integrated in GitHub or a continuous integration platform. In an ideal world, you select a range or matrix of setting you want to vary, and the 

So let's say you give a keyword like `compare -enc-mode [0 4 8] -q [15 30 45] -bit-depth 8`. Then the program runs SVT-AV1 on the master branch against SVT-AV1 with the PR applied, gathers visual and time metrics and compares them. It reports back, ideally in table form, so you get something like:

| BDR / speed      | PSNR  | MS SSIM | VMAF  | Real time | CPU time |
|------------------|-------|---------|-------|-----------|----------|
| enc-mode 0, q 15 | 92.7% | 81.8%   | 75.7% | -25.6%    | -87.5%   |
| enc-mode 0, q 30 | 40.8% | 76.3%   | 84.0% | -39.6%    | -89.7%   |
| enc-mode 0, q 45 | 40.4% | 43.5%   | 41.9% | -60.2%    | -59.3%   |
| enc-mode 4, q 15 | 49.4% | 2.9%    | 81.8% | -71.7%    | -16.1%   |
| enc-mode 4, q 30 | 37.2% | 78.2%   | 42.0% | -31.8%    | -12.8%   |
| enc-mode 4, q 45 | 40.5% | 0.3%    | 93.3% | -55.8%    | -61.0%   |
| enc-mode 8, q 15 | 62.9% | 36.1%   | 52.8% | -39.5%    | -71.5%   |
| enc-mode 8, q 30 | 78.8% | 52.2%   | 97.5% | -31.9%    | -29.2%   |
| enc-mode 8, q 45 | 58.9% | 64.0%   | 4.3%  | -61.8%    | -56.8%   |
| Average          | 55.7% | 48.4%   | 63.7% | -46.4%    | -53.8%   |

(100% fictional example)

Maybe the easiest way would be to even write our own CLI application for the command execution. And we need something like [probot](https://github.com/probot/probot) to report it back to GitHub.

As you can see, the get the most out of this it get's very complex quickly.

An easier initial implementation would be to create a binary identical check for each speed level, and run the comparison on each speed level dat didn't result identical reports. But in that case we shouldn't run it each commit, only once per PR.

**Comment by ultrawide** [comment]
@EwoutH No problem, thanks for the detailed response! It looks to me like the main idea is to be able to quickly compare PRs against master for quality and speed. I agree that it can get very complex quickly and also computationally expensive. How many clips to encode, which encode modes/QP to use, which metrics to employ would be something to consider as well.
 
Right now, I'm thinking about extending the binary identical check and exporting this data onto a web server/database with a unique identifier such as a commit hash. I'm not entirely proficient with these technologies and it would be good to know what speed impacts would be acceptable to add onto our the CI. 

I want to see what options are available and what what would be a good approach before making a prototype and researching further.

**Comment by EwoutH** [comment]
@ultrawide I think if you get this working @hassount and @kylophone going to throw all the compute power at you that you need, since this could hugely speed op development and especially tuning.

As of metrics, I think PSNR, MS SSIM and VMAF would be good for quality, Real time and CPU time for performance and maybe memory use.

Maybe we can start with just one or two videos, and once there is a proof of concept we can extent to the full [objective-1-fast](https://people.xiph.org/~tdaede/sets/objective-1-fast/) currently widely used.

The https://github.com/xiph/awcy repository might have some handy tools also.

**Comment by hassount** [comment]
> @ultrawide I think if you get this working @hassount and @kylophone going to throw all the compute power at you that you need, since this could hugely speed op development and especially tuning.
> 
> As of metrics, I think PSNR, MS SSIM and VMAF would be good for quality, Real time and CPU time for performance and maybe memory use.
> 
> Maybe we can start with just one or two videos, and once there is a proof of concept we can extent to the full [objective-1-fast](https://people.xiph.org/~tdaede/sets/objective-1-fast/) currently widely used.
> 
> The https://github.com/xiph/awcy repository might have some handy tools also.

Just need to make sure the the work @ePirat is doing does not conflict with this so that we don't have to do the work twice.

**Comment by mafonsoN** [comment]
@ePirat @ultrawide we need to add more encodes to github actions CI. Not sure if this was already discussed before, but right now only the binary tests are running any encodes. 

I've added two new sequences to video.tar.gz in SVT-AV1-resources repo which are 720p, 8-bit and 10-bit. This comes from the fact that we have found a few crashes that only happen for higher resolutions (>=720p). 

The command lines to run could be as follows [enc-mode 3]:

`./SvtAv1EncApp -i akiyo_720p_8bit_20frames.y4m -enc-mode 3 -n 20 -b test-pr-akiyo-720p-8bit-m3.ivf`

`./SvtAv1EncApp -i akiyo_720p_10bit_20frames.y4m -enc-mode 3 -n 20 -b test-pr-akiyo-720p-10bit-m3.ivf`

In addition, other problem is that when the binary identical tests fail, the entire CI is failing (x). This is not the behaviour we want since some of the PRs are supposed to change the bitstreams. Would it be possible to have a similar behaviour as the travis build? I quickly checked online but it doesn't seem to be supported in github actions. Can someone confirm?

Thanks!!!

**Comment by luigi311** [comment]
@mafonsoN we can mark the binary check as continue on fail but it will mark it as a checkmark apperently. I haven't had a chance to test it. We can also move the binary check to the very end so everything else will run and complete.

**Comment by luigi311** [comment]
Looks like we can do a base_script without anchor support. It doesn't look as nice since we have to declare it at the top and call it with an eval "$base_script" setup. Is this something you guys want to do? Here what it looks like so far with it on the build and binary check steps
https://github.com/luigi311/SVT-AV1/blob/actions_base_script/.github/workflows/svt-av1.yml

**Comment by 1480c1** [comment]
Perhaps we can just make a .ci folder with a ci.sh and add the stuff there

**Comment by luigi311** [comment]
So something similar to this https://github.com/luigi311/SVT-AV1/tree/actions_base_script/.github/workflows
but we can put it on the root folder under the .ci folder like you said. Only thing is we can not test this method on the binary check since that only checkouts master which this won't exist in.

**Comment by luigi311** [comment]
@ultrawide 
For the binary test it looks like you are pulling in master of the fork and not of the master of the official branch for the comparison.

```bash
Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: luigi311/SVT-AV1
Working directory is '/home/runner/work/SVT-AV1/SVT-AV1'
/usr/bin/git version
git version 2.25.0
Deleting the contents of '/home/runner/work/SVT-AV1/SVT-AV1'
/usr/bin/git init /home/runner/work/SVT-AV1/SVT-AV1
Initialized empty Git repository in /home/runner/work/SVT-AV1/SVT-AV1/.git/
/usr/bin/git remote add origin https://github.com/luigi311/SVT-AV1
/usr/bin/git config --local gc.auto 0
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/master*:refs/remotes/origin/master* +refs/tags/master*:refs/tags/master*
```

**Comment by ultrawide** [comment]
@luigi311 
Based on my understanding, the current implementation will compare the master of a fork against a push/pull from the same fork; that is, if someone makes a pull request on the official repo, it will compare the official master against their pull request. That was my intention. Please correct me if I'm wrong.

Do we want to extend the behavior to compare the official master for forked branches? Any thoughts?

**Comment by luigi311** [comment]
@ultrawide 
It looks like travis was configured to pull the official master instead of the master of the fork. I think the reasoning of this is the fact that forks can be old and master can be unmerged, I do all my development in another branch and merge that with the official master so in cases like this the forks master will never be updated and will remain out of date.
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/.travis.yml#L211

**Comment by luigi311** [comment]
@EwoutH 
Pinging you since you are the one that wrote the binary test for travis, do we want to do a binary check against the OpenVisualCloud master or the forks master? Right now we are doing a comparison against the fork master while travis is cloning the OpenVisualCloud master and comparing that to the PR build.

**Comment by hassount** [comment]
> @EwoutH
> Pinging you since you are the one that wrote the binary test for travis, do we want to do a binary check against the OpenVisualCloud master or the forks master? Right now we are doing a comparison against the fork master while travis is cloning the OpenVisualCloud master and comparing that to the PR build.

@luigi311 Thank you very much for bringing this up. The point of the test is to check whether we have changed the stream as compared to the master that the PR is being pulled to, that is very useful to test optimizations that are not supposed to change the output so can we change it to test the openvisual cloud master. One more item on this, can we make this test allowed to fail, because changing the bitstream is ok for the rest of the features.

**Comment by luigi311** [comment]
@hassount 
The problem with allow failure in github actions is that it will always end up with a green check mark and the only way to see if it has an error is to open up the test every single time. Can you explain what you want to see? For travis it works because on the PR you only see 1 test with all the "subtest"underneath it which you can control if you want all test to be required to pass for the main test to be considered a pass or if you are ok with certain "subtest" failing. For github actions there is no "main"/"subtest" instead they are all marked as "main" tests and are all displayed on the PR as individual tests so setting it to always green makes it hard to see the results from binary test easily.

**Comment by hassount** [comment]
@luigi311 
understood, having a green mark is definitely not ideal, that said having the build with an x shows that the build is broken, so in my opinion having it green, and having us double check when needed might work better.

**Comment by luigi311** [comment]
@hassount 
Makes sense to me. I will go ahead and implement it.

**Comment by luigi311** [comment]
Looks like e2e will randomly fail.
It is running fine here 
https://github.com/luigi311/SVT-AV1/runs/465148201?check_suite_focus=true
but for this commit it failed 
https://github.com/luigi311/SVT-AV1/runs/465261530?check_suite_focus=true
even though the change was for binary-identical-test and no other files were changed.

**Comment by luigi311** [comment]
Here is another example where it is failing on a document change
Here it is running sucessfully
https://github.com/OpenVisualCloud/SVT-AV1/actions/runs/44477571
One commit later with a document change it is now failing
https://github.com/OpenVisualCloud/SVT-AV1/actions/runs/44477520

**Comment by luigi311** [comment]
On my pull request for adding ffmpeg and gstreamer patches @ultrawide noticed that my binary check checkout was doing a merge from master into my fork while his CI on his own fork was not doing the merge and instead cloning master correctly. It looks the checkout action will function differently based on the type of even the shot it off. If the event that triggered the CI is the push event then it will function as expected and clone the repo specified and run its scripts, if the even is instead a pull request it will go and merge the fork into the repo that you specified. [Here is an example](https://github.com/OpenVisualCloud/SVT-AV1/pull/983/checks?check_run_id=465370838#step:4:27) of it doing the merge and if you noticed on the left it shows CI on: pull request. Where as [here is the same commit](https://github.com/luigi311/SVT-AV1/runs/465374762?check_suite_focus=true#step:4:27) on my fork with the CI on:push and it does not contain the merge command. While this might not be a problem most of the time it is a problem when you are cloning a repo and need that clone to be an exact replica of the repo. The merge that we observed was for the svt-av1 master branch which makes the merge easy, I am not sure how it will handle a merge on a third party repo such as ffmpeg so when you need to clone a repo that is not your fork and you are using the checkout action make sure you include the ref: {branch name} option or it will attempt to merge that repo with your fork.

**Comment by hassount** [comment]
Hi Guys,

can we add treating warnings as errors into the github actions scripts ?

**Comment by luigi311** [comment]
@hassount so on compilers like gcc you want to enable --Wall and --Werror?

**Comment by 1480c1** [comment]
It would be `-Wall` and `-Werror` but I think there was one warning we did not treat as an error

**Comment by hassount** [comment]
@luigi311 
basically, similar to what travis is doing:
https://github.com/OpenVisualCloud/SVT-AV1/blob/7f825cb0b097d01e5d65edf76c55d6621608a3f8/.travis.yml#L50

**Comment by luigi311** [comment]
@hassount 
Do you also want to use ```-Wall```? It does not look like it is being used in the travis build. By default unless it changed recently you do not get all warnings unless you use the ```-Wall``` flag

**Comment by ultrawide** [comment]
> > @ultrawide I think if you get this working @hassount and @kylophone going to throw all the compute power at you that you need, since this could hugely speed op development and especially tuning.
> > As of metrics, I think PSNR, MS SSIM and VMAF would be good for quality, Real time and CPU time for performance and maybe memory use.
> > Maybe we can start with just one or two videos, and once there is a proof of concept we can extent to the full [objective-1-fast](https://people.xiph.org/~tdaede/sets/objective-1-fast/) currently widely used.
> > The https://github.com/xiph/awcy repository might have some handy tools also.
> 
> Just need to make sure the the work @ePirat is doing does not conflict with this so that we don't have to do the work twice.

@ePirat Can you confirm above? Thanks!

**Comment by hassount** [comment]
Can we close this issue as we're moving to gitlab ?

**Comment by ePirat** [comment]
I would be in favor of closing it, for the undergoing CI work we can use https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1 to discuss that.

**Comment by EwoutH** [comment]
Yes, fine by me
